# print('8'+'1')
# nome= input('Digite seu nome: ')
# idade= int(input('Digite sua idade: '))
# peso= float(input('Digite seu peso: '))
# print(idade, nome, peso)

# nome= input('Digite seu nome: ')

# print(f'Olá {nome}, seja muito bem vindo')

# dia= int(input("que dia voce nasceu: "))
# mes= (input("que mes voce nasceu: "))
# ano= int(input("que ano voce nasceu: "))

# print(f"Você nasceu na data {dia}/{mes}/{ano}")

# num1 = int(input('Digite um num: '))
# num2 = int(input('Digite outro num: '))

# print(num1 + num2)
